version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: inventory-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
